---
title: "Concentration"
output: html_document
date: '2022-06-27'
---

```{r load-data}
library(tidyverse)
landings <- read_csv("~/Downloads/good_landings.csv")
```

```{r clean-df}
landings <- landings %>%
  rename(year = YEAR) %>%
  rename(port = "PORT NAME") %>%
  rename(state = STATE) %>%
  rename(sp_name = SPPNAME) %>%
  rename(landed_lbs = "LANDED LBS") %>%
  rename(live_lbs = "LIVE LBS") %>%
   rename(value = VALUE)
```

```{r filter-year}
landings <- landings %>%
  filter(year >= 1995)
```

```{r numeric-lbs}
###convert the landings data to numeric values

landings$landed_lbs <- gsub(",", "", landings$landed_lbs)
landings$landed_lbs <- as.integer(landings$landed_lbs)

landings$live_lbs <- gsub(",", "", landings$live_lbs)
landings$live_lbs <- as.integer(landings$live_lbs)


landings$value <- gsub(",", "", landings$value)
landings$value <- as.integer(gsub("\\$", "", landings$value))

landings$year <- as.integer(landings$year)

landings <- landings %>%
  select(year, port, state, sp_name, landed_lbs, live_lbs, value)
str(landings)
```

```{r port-state}
landings$port_state <- paste(landings$port, landings$state, sep = " ")
```  

```{r conf-species}
conf_landings <- landings %>%
  filter(sp_name == "CONFIDENTIAL") %>%
  group_by(year, port_state) %>%
  summarise(conf_lbs = sum(landed_lbs)) 
```  

```{r total-port-landings}
###total landings by port and year
total_port_landings <- landings %>%
  group_by(year, port_state) %>%
  summarise(total_lbs = sum(landed_lbs))
```

```{r join-dfs}
totals <- left_join(total_port_landings, conf_landings, by=c("year", "port_state")) 
totals$conf_lbs <- ifelse(is.na(totals$conf_lbs), 0, totals$conf_lbs)
```

```{r perc-annual-conf}
totals <- totals %>%
  mutate(perc_annual_conf = round(conf_lbs / total_lbs, 2))
```

```{r annual-above-50}
totals <- totals %>%
  mutate(yrs = 1,
         above50 = ifelse(perc_annual_conf >= 0.5, 1, 0)) 
```

```{r conf-yrs}
confyrs <- totals %>%
  group_by(port_state) %>%
  summarise(totalyrs = sum(yrs),
            yrsabove50 = sum(above50))
```

```{r perc-above}
perc_yrs <- confyrs %>%
  mutate(perc_above = round(yrsabove50 / totalyrs, 2))
```

```{r exclude-ports}
exclude <- perc_yrs %>%
  filter(perc_above >= 0.5)
```

```{r include-ports}
include <- perc_yrs %>%
  filter(perc_above < 0.5, totalyrs > 6)
```

```{r yrs-ports}
landings <- landings %>%
  filter(port_state %in% include$port_state)

```



-------------------------------------------------------------------------
THEIL

```{r dummy-package}
library(REAT)
library(dineq)

dummy <- data.frame(
  port = letters[1:6],
  value = c(10, 10, 10, 20, 500, 7000))

#differences in weighting? think bottom may be right, don't understand why the top still isnt working
theil(dummy$value)
theil.wtd(dummy$value, weights = NULL) #working like own code
theil.wtd(dummy$value, weights = dummy$value)
```

```{r theil-code}

dummy <- mutate(dummy, share = (value / sum(dummy$value)),
                share_mean = share * n_distinct(port), 
                t_value = log(share_mean)*share)
  
dummy %>%
  summarise(sum(t_value))

```

```{r from-package-2019}
theil_2019 <- landings %>%
  filter(sp_name == "COD, ATLANTIC", year == 2019) 

#why negative? not sure
theil(theil_2019$value) #abs
theil(theil_2019$value, weighting = theil_2019$value)
theil.wtd(theil_2019$value, weights = NULL) #THIS MATCHES WHAT I GET...STILL CANNOT BE CORRECT
theil.wtd(theil_2019$value, weights = theil_2019$value)
```

```{r theil-2019-code}
theil_2019 <- mutate(theil_2019, share = (value / sum(theil_2019$value)),
                     share_mean = share *n_distinct(port_state),
                     contribution = log(share_mean)*share)
  
theil_2019 %>%
  summarise(sum(contribution))

```

```{r theil-func}
library(dineq)

theil_func <- function(yr, name) {
  x <- filter(landings, year == yr, sp_name == name)
  
  x <- aggregate(cbind(value) ~ port_state, data = x, FUN = sum)
  
  value <- theil.wtd(x$value, weights = NULL)
  value <- as.double(value)
  print(value)
}

theil_results = data.frame()

years_list = 1995:2021
species_list <- c("COD, ATLANTIC", "LOBSTER, AMERICAN", "HADDOCK", "FLOUNDER, SUMMER", "SEA BASS, BLACK")

for(i in years_list) {
    for(j in species_list) {
  output = c(i, j, theil_func(i, j))
  theil_results = rbind(theil_results, output)
    }

}

colnames(theil_results)<-c("year", "name", "index")
theil_results$year <- as.integer(theil_results$year)
theil_results$index <- as.double(theil_results$index)

```

```{r theil-viz-facet}
colnames(theil_results)<-c("year", "name", "index")

theil_results %>%
  ggplot(aes(year, index)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "",
       y = "Absolute Theil Index",
       title = "") +
  facet_wrap(~ name, ncol = 3) +
  theme_minimal()
```

```{r}
  
theil_2019 %>%
  group_by(port_state) %>%
  ggplot(aes(share)) +
  geom_density() 
```

```{r}
share_func <- function(yr, name) {
  x <- filter(landings, year == yr, sp_name == name)
  x <- aggregate(cbind(value) ~ port_state, data = x, FUN = sum)
  
  share = value / sum(x$value)
    
  share <- as.double(share) 

  print(share)
}
```

