```{r load-data}
library(readxl)
library(tidyverse)
landings <- read_excel("~/Desktop/GMRI/landings_excel.xlsx")
view(landings)
```

```{r clean-df}
landings <- landings %>%
  rename(year = YEAR) %>%
  rename(port = "PORT NAME") %>%
  rename(state = STATE) %>%
  rename(sp_name = SPPNAME) %>%
  rename(landed_lbs = "LANDED LBS") %>%
  rename(live_lbs = "LIVE LBS") %>%
   rename(value = VALUE)
```
```{r filter-year}
landings <- landings %>%
  filter(year >= 1995)
```

```{r numeric-lbs}
###convert the landings data to numeric values

landings$landed_lbs <- gsub(",", "", landings$landed_lbs)
landings$landed_lbs <- as.integer(landings$landed_lbs)

landings$live_lbs <- gsub(",", "", landings$live_lbs)
landings$live_lbs <- as.integer(landings$live_lbs)


landings$value <- gsub(",", "", landings$value)
landings$value <- as.integer(gsub("\\$", "", landings$value))

landings$year <- as.integer(landings$year)
str(landings)
```
```{r lobster-landings}
###lobster ONLY landings by year and state --> for visualization
lobster_landings <- landings %>%
  filter(sp_name == "LOBSTER, AMERICAN") %>%
  group_by(state, year) %>%
  summarise(lobster_lbs = sum(landed_lbs))
```


```{r total-state-landings}
###total landings by port and year
total_landings <- landings %>%
  filter(port != "CONFIDENTIAL") %>%
  group_by(year, state) %>%
  summarise(total_lbs = sum(landed_lbs)) %>%
  
  view()
```

```{r lobster-viz}
lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    color = ""
  ) #+
  #scale_x_continuous(breaks = 1995:2021) +
 # scale_y_continuous(labels = c(0, 25, 50, 75))
```

```{r lobster-viz-proportions}

lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, fill = state)) +
  geom_col(position="fill") +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y="",
    fill = ""
  )
```

```{r lobster-viz-stacked}

lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y = "",
    fill = ""
  )
```
```{r lobster-viz-newengland}

lobster_landings %>%
  filter(state != "ME", state != "DE", state != "ME", state != "VA", state != "NC") %>%
  ggplot(aes(x = year, y = lobster_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in New England + NH, 1995-2021",
    x = "Year",
    y = "Landed Pounds",
    color = "State"
  )
```
```{r lobster-viz-maine}

lobster_landings %>%
  filter(state == "ME") %>%
  ggplot(aes(x = year, y = lobster_lbs)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in Maine, 1995-2021",
    x = "Year",
    y = "Landed Pounds"
  )
```
----------------------------------------------------
```{r port-state}
landings$port_state <- paste(landings$port, landings$state, sep = " ")
```  

```{r conf-species}
conf_landings <- landings %>%
  filter(sp_name == "CONFIDENTIAL") %>%
  group_by(year, port_state) %>%
  summarise(conf_lbs = sum(landed_lbs)) 
```  

```{r total-port-landings}
###total landings by port and year
total_port_landings <- landings %>%
  group_by(year, port_state) %>%
  summarise(total_lbs = sum(landed_lbs))
```

```{r join-dfs}
totals <- left_join(total_port_landings, conf_landings, by=c("year", "port_state")) 
totals$conf_lbs <- ifelse(is.na(totals$conf_lbs), 0, totals$conf_lbs)
```

```{r perc-annual-conf}
totals <- totals %>%
  mutate(perc_annual_conf = round(conf_lbs / total_lbs, 2))
```

```{r annual-above-50}
totals <- totals %>%
  mutate(yrs = 1,
         above50 = ifelse(perc_annual_conf >= 0.5, 1, 0)) 
```

```{r conf-yrs}
confyrs <- totals %>%
  group_by(port_state) %>%
  summarise(totalyrs = sum(yrs),
            yrsabove50 = sum(above50))
```

```{r perc-above}
perc_yrs <- confyrs %>%
  mutate(perc_above = round(yrsabove50 / totalyrs, 2))
```

```{r exclude-ports}
exclude <- perc_yrs %>%
  filter(perc_above >= 0.5)
```

```{r include-ports}
include <- perc_yrs %>%
  filter(perc_above < 0.5, totalyrs > 6)
```

```{r total-yrs-viz}
include %>%
  ggplot(aes(x = totalyrs)) +
  geom_bar()
```

```{r yrs-ports}
landings %>%
  filter(port_state %in% include$port_state)
```
```{r dummy}
library(REAT)
##NEED to better understand how this function works, the value should be between 0 and 1 and doesnt work on dummy it seems
dummy <- data.frame(
  year = 2000:2004,
  port = letters[1:5],
  value = c(1000, 1000, 50000, 1000, 10000))
  #share = c(0.01587, 0.01587, 0.7936, 0.01587, 0.1587))


#dummy <- mutate(dummy, share = 1 /(value / sum(dummy$value)))

theil(dummy$value)
#theil(1/dummy$value, weighting = dummy$value)
```

```{r theil function}
##POTENTIALLY REMAKE THIS FUNCTION

function (x, weighting = NULL, na.rm = TRUE) 
  {
  
    if (!is.null(weighting)) {
      
        if (length(x) != length(weighting)) {
          
            stop("Frequency and weighting differ in length", 
                 
                call. = FALSE)
          
        }
    }
  
    if (na.rm == TRUE) {
      
        if (!is.null(weighting)) {

            x_w <- as.matrix(cbind(x, weighting))

            x_w <- x_w[complete.cases(x_w), ]

            x <- x_w[, 1]

            weighting <- x_w[, 2]

        }

        else {

            x <- x[!is.na(x)]

        }

    }

    if (any((x) <= 0)) {

        return(NA)

    }

    x_mean <- mean2(x, na.rm = na.rm)

    if (!is.null(weighting)) {

        w_share <- weighting/sum(weighting)

        ln_mean <- w_share * log(x_mean/x)

    }

    else {
      
        ln_mean <- log(x_mean/x)
        
    }
  
    TE <- mean2(ln_mean, na.rm = na.rm)
    return(TE)

  }
```

```{r theil-practice}

theil_2019 <- landings %>%
  filter(sp_name == "COD, ATLANTIC", year == 2019) 

#theil_2019 <- mutate(theil_2019, share = 1 /(value / sum(theil_2019$value)))

#abs 
theil(1/theil_2019$value)
#relative
theil(1/theil_2019$value, weighting = theil_2019$value)
```
```{r }

theil_2004 <- landings %>%
  filter(sp_name == "COD, ATLANTIC", year == 2004) 

#theil_2019 <- mutate(theil_2019, share = 1 /(value / sum(theil_2019$value)))

#abs 
theil(1 / theil_2004$value)
#relative
theil(1/theil_2004$value, weighting = theil_2004$value)
```



