---
title: "Viz"
output: html_document
date: '2022-06-27'
---


```{r load-data}
library(tidyverse)
landings <- read_csv("~/Downloads/good_landings.csv")
```

```{r clean-df}
landings <- landings %>%
  rename(year = YEAR) %>%
  rename(port = "PORT NAME") %>%
  rename(state = STATE) %>%
  rename(sp_name = SPPNAME) %>%
  rename(landed_lbs = "LANDED LBS") %>%
  rename(live_lbs = "LIVE LBS") %>%
   rename(value = VALUE)
```

```{r filter-year}
landings <- landings %>%
  filter(year >= 1995)
```


```{r numeric-lbs}
###convert the landings data to numeric values

landings$landed_lbs <- gsub(",", "", landings$landed_lbs)
landings$landed_lbs <- as.integer(landings$landed_lbs)

landings$live_lbs <- gsub(",", "", landings$live_lbs)
landings$live_lbs <- as.integer(landings$live_lbs)


landings$value <- gsub(",", "", landings$value)
landings$value <- as.integer(gsub("\\$", "", landings$value))

landings$year <- as.integer(landings$year)

landings <- landings %>%
  select(year, port, state, sp_name, landed_lbs, live_lbs, value)
str(landings)
```

```{r port-state}
landings$port_state <- paste(landings$port, landings$state, sep = " ")
```  

```{r conf-species}
conf_landings <- landings %>%
  filter(sp_name == "CONFIDENTIAL") %>%
  group_by(year, port_state) %>%
  summarise(conf_lbs = sum(landed_lbs)) 
```  

```{r total-port-landings}
###total landings by port and year
total_port_landings <- landings %>%
  group_by(year, port_state) %>%
  summarise(total_lbs = sum(landed_lbs))
```

```{r join-dfs}
totals <- left_join(total_port_landings, conf_landings, by=c("year", "port_state")) 
totals$conf_lbs <- ifelse(is.na(totals$conf_lbs), 0, totals$conf_lbs)
```

```{r perc-annual-conf}
totals <- totals %>%
  mutate(perc_annual_conf = round(conf_lbs / total_lbs, 2))
```

```{r annual-above-50}
totals <- totals %>%
  mutate(yrs = 1,
         above50 = ifelse(perc_annual_conf >= 0.5, 1, 0)) 
```

```{r conf-yrs}
confyrs <- totals %>%
  group_by(port_state) %>%
  summarise(totalyrs = sum(yrs),
            yrsabove50 = sum(above50))
```

```{r perc-above}
perc_yrs <- confyrs %>%
  mutate(perc_above = round(yrsabove50 / totalyrs, 2))
```

```{r exclude-ports}
exclude <- perc_yrs %>%
  filter(perc_above >= 0.5)
```

```{r include-ports}
include <- perc_yrs %>%
  filter(perc_above < 0.5, totalyrs > 6)
```

```{r yrs-ports}
landings <- landings %>%
  filter(port_state %in% include$port_state)
```


```{r total-state-landings}
###total landings by port and year
total_landings <- landings %>%
  filter(port_state != "CONFIDENTIAL") %>%
  group_by(year, state) %>%
  summarise(total_lbs = sum(landed_lbs)) 
```

```{r lobster-viz-proportions}
lobster_landings <- landings %>%
  filter(sp_name == "LOBSTER, AMERICAN") %>%
  group_by(year, state) %>%
  summarise(lobster_lbs = sum(landed_lbs))
```

```{r}
lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y="Millions of Pounds",
    color = ""
  ) +
  scale_y_continuous(breaks = c(0, 50000000, 100000000, 150000000), labels = c(0, 50, 100, 150)) +
  theme_minimal()
  
```


```{r}
 lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, fill = state)) +
  geom_col(position="fill") +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y="",
    fill = ""
  )
```



```{r lobster-viz-stacked}

lobster_landings %>%
  ggplot(aes(x = year, y = lobster_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of American Lobster in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    fill = ""
  ) +
  scale_y_continuous(breaks = c(0, 50000000, 100000000, 150000000), labels = c(0, 50, 100, 150)) +
  theme_minimal()
```

```{r lobster-viz-newengland}

lobster_landings %>%
  filter(state != "ME", state != "DE", state != "ME", state != "VA", state != "NC") %>%
  ggplot(aes(x = year, y = lobster_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in New England + NH, 1995-2021",
    x = "Year",
    y = "Landed Pounds",
    color = "State"
  )
```

```{r lobster-viz-maine}

lobster_landings %>%
  filter(state == "ME") %>%
  ggplot(aes(x = year, y = lobster_lbs)) +
  geom_line() +
  labs(
    title = "Landed Pounds of American Lobster in Maine, 1995-2021",
    x = "Year",
    y = "Landed Pounds"
  )
```
```{r cod}
cod_landings <- landings %>%
  filter(sp_name == "COD, ATLANTIC") %>%
  group_by(year, state) %>%
  summarise(cod_lbs = sum(landed_lbs))
  
cod_landings %>%
  ggplot(aes(x = year, y = cod_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of Atlantic Cod in Northeastern U.S., 1995-2021",
    x = "",
    y="Millions of Pounds",
    color = ""
  ) +
  scale_y_continuous(breaks = c(0, 5000000, 10000000, 15000000, 20000000), labels = c(0, 5, 10, 15, 20)) +
  theme_minimal()
  
```

```{r cod-viz-stacked}

cod_landings %>%
  ggplot(aes(x = year, y = cod_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of Atlantic Cod in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    fill = ""
  ) +
  scale_y_continuous(breaks = c(0, 5000000, 10000000, 15000000, 20000000, 25000000), labels = c(0, 5, 10, 15, 20, 25)) +
  theme_minimal()
```

```{r haddock}
haddock_landings <- landings %>%
  filter(sp_name == "HADDOCK") %>%
  group_by(year, state) %>%
  summarise(haddock_lbs = sum(landed_lbs))
  
haddock_landings %>%
  ggplot(aes(x = year, y = haddock_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of Haddock in Northeastern U.S., 1995-2021",
    x = "",
    y="Millions of Pounds",
    color = ""
  ) +
  scale_y_continuous(breaks = c(0, 5000000, 10000000, 15000000, 20000000), labels = c(0, 5, 10, 15, 20)) +
  theme_minimal()
  
```

```{r haddock-viz-stacked}

haddock_landings %>%
  ggplot(aes(x = year, y = haddock_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of Haddock in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    fill = ""
  ) +
  scale_y_continuous(breaks = c(0, 5000000, 10000000, 15000000, 20000000), labels = c(0, 5, 10, 15, 20)) +
  theme_minimal()
```

```{r flounder}
flounder_landings <- landings %>%
  filter(sp_name == "FLOUNDER, SUMMER") %>%
  group_by(year, state) %>%
  summarise(flounder_lbs = sum(landed_lbs))
  
flounder_landings %>%
  ggplot(aes(x = year, y = flounder_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of Summer Flounder in Northeastern U.S., 1995-2021",
    x = "",
    y="Millions of Pounds",
    color = ""
  ) +
  scale_y_continuous(breaks = c(0, 2000000, 4000000), labels = c(0, 2, 4)) +
  theme_minimal()
  
```

```{r flounder-viz-stacked}

flounder_landings %>%
  ggplot(aes(x = year, y = flounder_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of Summer Flounder in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    fill = ""
  ) +
  scale_y_continuous(breaks = c(0, 5000000, 10000000, 15000000), labels = c(0, 5, 10, 15)) +
  theme_minimal()
```

```{r bass}
bass_landings <- landings %>%
  filter(sp_name == "SEA BASS, BLACK") %>%
  group_by(year, state) %>%
  summarise(bass_lbs = sum(landed_lbs))
  
bass_landings %>%
  ggplot(aes(x = year, y = bass_lbs, color = state)) +
  geom_line() +
  labs(
    title = "Landed Pounds of Black Sea Bass in Northeastern U.S., 1995-2021",
    x = "",
    y="Millions of Pounds",
    color = ""
  ) +
  theme_minimal()
  
```

```{r bass-viz-stacked}

bass_landings %>%
  ggplot(aes(x = year, y = bass_lbs, fill = state)) +
  geom_bar(position="stack", stat="identity") +
  labs(
    title = "Landed Pounds of Black Sea Bass in Northeastern U.S., 1995-2021",
    x = "",
    y = "Millions of Pounds",
    fill = ""
  ) +
  scale_y_continuous(breaks = c(0, 1000000, 2000000, 3000000, 4000000), labels = c(0, 1, 2, 3, 4)) +
  theme_minimal()
```

